image: $REGISTRY_CI/gitlab-ci-base:buster

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_DEPTH: 10

services:
  - docker:19.03.1-dind

stages:
  - build-test
  - test
  - build
  - deploy

#########################
####  TEMPLATE      ####
########################

.test_template: &test_definition
  allow_failure: false
  before_script:
    - sed -i -e "s/{SMTP_LINK\}/common-smtp:1025/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{ACTIVE_METHODS\}/$ACTIVE_METHODS/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{GITHUB_API_TOKEN\}/$GITHUB_TOKEN/" ./bin/docker/conf/test/auth.env.sample
    - sed -i -e "s/{GITLAB_API_TOKEN\}/$GITLAB_API_TOKEN/" ./bin/docker/conf/test/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PUBLIC_KEY\}/$MAGE_ACCOUNT_PUBLIC_KEY/" ./bin/docker/conf/test/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PRIVATE_KEY\}/$MAGE_ACCOUNT_PRIVATE_KEY/" ./bin/docker/conf/test/auth.env.sample
    - sed -i "s/$(echo "{BRANCH}" | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $CI_COMMIT_REF_NAME | sed -e 's/[\/&]/\\&/g')/g" ./bin/docker/conf/test/module.env.sample
    - sed -i -e "s@{PI_CI_DATA_URL\}@$PI_CI_DATA_URL@" ./bin/docker/conf/test/hipay.env.sample
  tags:
    - gcp-default-runner-prod
  artifacts:
    paths:
      - bin/tests/errors
    when: always

build-test-2-1-10:
  stage: build-test
  script:
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml push
  tags:
    - gcp-default-runner-prod

casperjs-2-1-10:
  <<: *test_definition
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml pull -q
    - docker-compose -f docker-compose.test.yml up -d
    - until docker-compose -f docker-compose.test.yml logs | grep -m 1 "DOCKER MAGENTO TO HIPAY stage IS UP" ; do sleep 1 ; done
    - docker-compose -f docker-compose.test.yml logs
    - curl --retry 10 --retry-delay 20 -v http:\/\/127.0.0.1:8096/
    - sh bin/tests/casper_run_circle.sh http:\/\/127.0.0.1:8096
  tags:
    - gcp-high-load-runner-prod

build:
  stage: build
  when: manual
  before_script:
    - /tools/docker-rmi.sh ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
  script:
    - docker-compose -f docker-compose.acceptance.yml build --no-cache
    - docker-compose -f docker-compose.acceptance.yml push
  after_script:
    - docker rmi ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
  tags:
    - gcp-default-runner-prod

deploy2recette:
  stage: deploy
  when: manual
  before_script:
    - sed -i -e "s/{PORT_WEB\}/$PORT_WEB/" ./bin/docker/conf/acceptance/mage.env.sample
    - sed -i -e "s/{SMTP_LINK\}/common-smtp:1025/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_RE7/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{ACTIVE_METHODS\}/$ACTIVE_METHODS/" ./bin/docker/conf/acceptance/hipay.env.sample
    - sed -i -e "s/{GITHUB_API_TOKEN\}/$GITHUB_TOKEN/" ./bin/docker/conf/acceptance/auth.env.sample
    - sed -i -e "s/{GITLAB_API_TOKEN\}/$GITLAB_API_TOKEN/" ./bin/docker/conf/acceptance/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PUBLIC_KEY\}/$MAGE_ACCOUNT_PUBLIC_KEY/" ./bin/docker/conf/acceptance/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PRIVATE_KEY\}/$MAGE_ACCOUNT_PRIVATE_KEY/" ./bin/docker/conf/acceptance/auth.env.sample
    - sed -i "s/$(echo "{BRANCH}" | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $CI_COMMIT_REF_NAME | sed -e 's/[\/&]/\\&/g')/g" ./bin/docker/conf/acceptance/module.env.sample
    - sed -i -e "s/{DB_HOST\}/${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_database/" ./bin/docker/conf/acceptance/mage.env.sample
    - sed -i -e "s/{MAGENTO_URL\}/http:\/\/${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com/" ./bin/docker/conf/acceptance/mage.env.sample
    - sed -i -e "s/{MAGENTO_URL_SECURE\}/https:\/\/${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com/" ./bin/docker/conf/acceptance/mage.env.sample
    - sed -i -e "s@{PI_CI_DATA_URL\}@$PI_CI_DATA_URL@" ./bin/docker/conf/acceptance/hipay.env.sample
    # Substitute env variables which doesn't exists on the distant machine
    - /tools/substitute-env-var.sh docker-compose.acceptance.yml
    # Change path for relative path to environment files
    - sed -i -e "s|bin/docker/conf/acceptance/hipay.env.sample|hipay.env.sample|g" docker-compose.acceptance.yml
    - sed -i -e "s|bin/docker/conf/acceptance/auth.env.sample|auth.env.sample|g" docker-compose.acceptance.yml
    - sed -i -e "s|bin/docker/conf/acceptance/mage.env.sample|mage.env.sample|g" docker-compose.acceptance.yml
    - sed -i -e "s|bin/docker/conf/acceptance/module.env.sample|module.env.sample|g" docker-compose.acceptance.yml
  script:
    - bash /tools/deployToDockerMachine.sh -e ./bin/docker/conf/acceptance/hipay.env.sample -e ./bin/docker/conf/acceptance/auth.env.sample -e ./bin/docker/conf/acceptance/mage.env.sample -e ./bin/docker/conf/acceptance/module.env.sample -s docker-compose.acceptance.yml -n $DOCKER_STACK-$DOCKER_SERVICE-$CI_COMMIT_REF_SLUG
  allow_failure: true
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http:\/\/${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com/
  tags:
    - gcp-default-runner-prod
