version: "3.3"

services:
  web:
    image: $REGISTRY_CI/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
    build:
      context: .
      dockerfile: ./bin/docker/images/default/Dockerfile
    depends_on:
      - database
    env_file:
      - ./bin/docker/conf/test/hipay.env.sample
      - ./bin/docker/conf/test/auth.env.sample
      - ./bin/docker/conf/test/mage.env.sample
      - ./bin/docker/conf/test/module.env.sample
    ports:
      - "8096:80"

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3308:3306"
